version: '3.8'

networks:
  api-network:
    driver: bridge

services:
  postgres:
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgressql/data
    hostname: localhost
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - api-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - api-network
  
  app:
    volumes:
      - ./:/usr/src/app
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - postgres
    networks:
      - api-network

volumes:
    pgdata: